Add Collector's sanity check workflow

diff --git a/.github/workflows/pre-main.yaml b/.github/workflows/pre-main.yaml
--- a/.github/workflows/pre-main.yaml
+++ b/.github/workflows/pre-main.yaml
@@ -164,3 +164,118 @@ jobs:
         if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'redhat-best-practices-for-k8s' }}
         with:
           ssh-private-key: ${{ secrets.COLLECTOR_KEYPAIR }}
+
+  sanity-check:
+    name: Run Collector's sanity check
+    runs-on: ubuntu-22.04
+    env:
+      SHELL: /bin/bash
+      KUBECONFIG: '/home/runner/.kube/config'
+      PFLT_DOCKERCONFIG: '/home/runner/.docker/config'
+
+    steps:
+      - name: Write temporary docker file
+        run: |
+          mkdir -p /home/runner/.docker
+          touch ${PFLT_DOCKERCONFIG}
+          echo '{ "auths": {} }' >> ${PFLT_DOCKERCONFIG}
+
+      # needed by depends-on-action
+      - name: Set up Go 1.23
+        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
+        with:
+          go-version: 1.23.1
+
+      # Perform smoke tests using a Certsuite container.
+      - name: Check out code
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          ref: ${{ github.sha }}
+
+      - name: Check out `certsuite`
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          repository: redhat-best-practices-for-k8s/certsuite
+          path: certsuite
+
+      - name: Setup partner cluster
+        uses: ./.github/actions/setup-partner-cluster
+        with:
+          working_directory: certsuite
+          make-command: 'install'
+
+      - name: Extract dependent Pull Requests
+        uses: depends-on/depends-on-action@9e8a61fce18b15281e831f1bba0e14c71d1e1f46 # main
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      # Clean up unused container image layers. We need to filter out a possible error return code
+      # from docker with "|| true" as some images might still be used by running kind containers and
+      # will not be removed.
+      - name: Remove unnamed/dangling container images to save space. Show disk space before and after removing them.
+        run: |
+          df -h
+          docker rmi $(docker images -f "dangling=true" -q) || true
+          df -h
+
+      - name: Create required Certsuite config files and directories
+        run: |
+          mkdir -p $CERTSUITE_CONFIG_DIR $CERTSUITE_OUTPUT_DIR
+          cp /home/runner/.kube/config $CERTSUITE_CONFIG_DIR/kubeconfig
+          cp /home/runner/.docker/config $CERTSUITE_CONFIG_DIR/dockerconfig
+          cp config/*.yml $CERTSUITE_CONFIG_DIR
+        shell: bash
+
+      - name: Get Collector's CI credentials
+        run: |
+          echo "collector_ciuser=ciuser_${{ github.run_id }}" >> $GITHUB_OUTPUT
+          echo "collector_cipassword=cipassword" >> $GITHUB_OUTPUT
+        id: set_collector_ci_creds
+
+      - name: Update Collector's CI credentials and Print username
+        run: |
+          echo Collector CI username: ${{ steps.set_collector_ci_creds.outputs.collector_ciuser }}
+          echo "COLLECTOR_CIUSER=${{ steps.set_collector_ci_creds.outputs.collector_ciuser }}" >> $GITHUB_ENV
+          echo "COLLECTOR_CIPASSWORD=${{ steps.set_collector_ci_creds.outputs.collector_cipassword }}" >> $GITHUB_ENV
+
+      - name: Ensure COLLECTOR_CIUSER and COLLECTOR_CIPASSWORD are set
+        run: '[[ -n "$COLLECTOR_CIUSER" ]] && [[ -n "$COLLECTOR_CIPASSWORD" ]]'
+
+      - name: Modify Certsuite config with CI collector credentials
+        run: |
+          sed -i\
+            -e '/executedBy/s/""/"CI"/g' \
+            -e '/partnerName/s/""/"${{ env.COLLECTOR_CIUSER }}"/g' \
+            -e '/collectorAppPassword/s/""/"${{ env.COLLECTOR_CIPASSWORD }}"/g' \
+            $CERTSUITE_CONFIG_DIR/certsuite_config.yml
+
+      - name: 'Test: Run Smoke Tests in a Certsuite container with the certsuite command'
+        run: |
+          docker run --rm --network host \
+            -v $CERTSUITE_CONFIG_DIR:/usr/certsuite/config:Z \
+            -v $CERTSUITE_OUTPUT_DIR:/usr/certsuite/output:Z \
+            ${REGISTRY_LOCAL}/${CERTSUITE_IMAGE_NAME}:${CERTSUITE_IMAGE_TAG} \
+            certsuite run \
+            --output-dir=/usr/certsuite/output \
+            --preflight-dockerconfig=/usr/certsuite/config/dockerconfig \
+            --offline-db=/usr/offline-db \
+            --enable-data-collection=true \
+            --log-level=${SMOKE_TESTS_LOG_LEVEL} \
+            --config-file=/usr/certsuite/config/certsuite_config.yml \
+            --kubeconfig=/usr/certsuite/config/kubeconfig \
+            --label-filter="${SMOKE_TESTS_LABELS_FILTER}"
+
+      - name: Run sanity check on collector
+        uses: ./collector/.github/actions/run-sanity-check
+        with:
+          collector_username: ${COLLECTOR_CIUSER}
+          collector_password: ${COLLECTOR_CIPASSWORD}
+        continue-on-error: true
+
+      # - name: Send chat msg to dev team if collector's sanity check failed.
+      #   if: ${{ steps.collector_sanity_check.outcome == 'failure' }}
+      #   uses: ./.github/actions/slack-webhook-sender
+      #   with:
+      #     working_directory: certsuite
+      #     message: 'Collector sanity check has failed'
+      #     slack_webhook: '${{ secrets.SLACK_ALERT_WEBHOOK_URL }}'
