Add Collector's sanity check workflow (#360)
* Add Collector's sanity check workflow

* add certsuite image name and tag env vars

* fix set up cluster checkout out

* fix set certsuite config and output dir

* add config file from certsuite repo

* add tmate session

* add smote tests label filter; diable tmate

* fix sanity check dir

* send slack msg if anity check fails

* add sanity check job id

* run smoke tests on PR with both latest and unstable certsuite images; send msg to slack when curl fails instead

diff --git a/.github/workflows/pre-main.yaml b/.github/workflows/pre-main.yaml
--- a/.github/workflows/pre-main.yaml
+++ b/.github/workflows/pre-main.yaml
@@ -13,6 +13,10 @@ env:
   COLLECTOR_IMAGE_NAME: redhat-best-practices-for-k8s/collector
   COLLECTOR_IMAGE_TAG: unstable
   COLLECTOR_IMAGE_NAME_LEGACY: testnetworkfunction/collector
+  CERTSUITE_IMAGE_NAME: redhat-best-practices-for-k8s/certsuite
+  CERTSUITE_CONFIG_DIR: /tmp/certsuite/config
+  CERTSUITE_OUTPUT_DIR: /tmp/certsuite/output
+  SMOKE_TESTS_LABELS_FILTER: all
 jobs:
   lint:
     name: Run Linter and Vet
@@ -164,3 +168,105 @@ jobs:
         if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'redhat-best-practices-for-k8s' }}
         with:
           ssh-private-key: ${{ secrets.COLLECTOR_KEYPAIR }}
+
+  sanity-check:
+    name: Run Collector's sanity check
+    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        certsuite_img_tag: [unstable, latest]
+    env:
+      SHELL: /bin/bash
+      KUBECONFIG: '/home/runner/.kube/config'
+      PFLT_DOCKERCONFIG: '/home/runner/.docker/config'
+
+    steps:
+      - name: Write temporary docker file
+        run: |
+          mkdir -p /home/runner/.docker
+          touch ${PFLT_DOCKERCONFIG}
+          echo '{ "auths": {} }' >> ${PFLT_DOCKERCONFIG}
+
+      # Perform smoke tests using a Certsuite container.
+      - name: Check out code
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
+        with:
+          ref: ${{ github.sha }}
+
+      - name: Check out `certsuite`
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
+        with:
+          repository: redhat-best-practices-for-k8s/certsuite
+          path: certsuite
+
+      - name: Setup partner cluster
+        uses: ./certsuite/.github/actions/setup-partner-cluster
+        with:
+          working_directory: certsuite
+          make-command: 'install'
+
+      # Clean up unused container image layers. We need to filter out a possible error return code
+      # from docker with "|| true" as some images might still be used by running kind containers and
+      # will not be removed.
+      - name: Remove unnamed/dangling container images to save space. Show disk space before and after removing them.
+        run: |
+          df -h
+          docker rmi $(docker images -f "dangling=true" -q) || true
+          df -h
+
+      - name: Create required Certsuite config files and directories
+        run: |
+          mkdir -p $CERTSUITE_CONFIG_DIR $CERTSUITE_OUTPUT_DIR
+          cp /home/runner/.kube/config $CERTSUITE_CONFIG_DIR/kubeconfig
+          cp /home/runner/.docker/config $CERTSUITE_CONFIG_DIR/dockerconfig
+          cp certsuite/config/*.yml $CERTSUITE_CONFIG_DIR
+        shell: bash
+
+      - name: Get Collector's CI credentials
+        run: |
+          echo "collector_ciuser=ciuser_${{ matrix.certsuite_img_tag }}_${{ github.run_id }}" >> $GITHUB_OUTPUT
+          echo "collector_cipassword=cipassword" >> $GITHUB_OUTPUT
+        id: set_collector_ci_creds
+
+      - name: Update Collector's CI credentials and Print username
+        run: |
+          echo Collector CI username: ${{ steps.set_collector_ci_creds.outputs.collector_ciuser }}
+          echo "COLLECTOR_CIUSER=${{ steps.set_collector_ci_creds.outputs.collector_ciuser }}" >> $GITHUB_ENV
+          echo "COLLECTOR_CIPASSWORD=${{ steps.set_collector_ci_creds.outputs.collector_cipassword }}" >> $GITHUB_ENV
+
+      - name: Ensure COLLECTOR_CIUSER and COLLECTOR_CIPASSWORD are set
+        run: '[[ -n "$COLLECTOR_CIUSER" ]] && [[ -n "$COLLECTOR_CIPASSWORD" ]]'
+
+      - name: Modify Certsuite config with CI collector credentials
+        run: |
+          sed -i\
+            -e '/executedBy/s/""/"CI"/g' \
+            -e '/partnerName/s/""/"${{ env.COLLECTOR_CIUSER }}"/g' \
+            -e '/collectorAppPassword/s/""/"${{ env.COLLECTOR_CIPASSWORD }}"/g' \
+            $CERTSUITE_CONFIG_DIR/certsuite_config.yml
+
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
+
+      - name: 'Run Smoke Tests in a Certsuite unstable container with the certsuite command'
+        run: |
+          docker run --rm --network host \
+            -v $CERTSUITE_CONFIG_DIR:/usr/certsuite/config:Z \
+            -v $CERTSUITE_OUTPUT_DIR:/usr/certsuite/output:Z \
+            ${REGISTRY}/${CERTSUITE_IMAGE_NAME}:${{ matrix.certsuite_img_tag }} \
+            certsuite run \
+            --output-dir=/usr/certsuite/output \
+            --preflight-dockerconfig=/usr/certsuite/config/dockerconfig \
+            --offline-db=/usr/offline-db \
+            --enable-data-collection=true \
+            --log-level=${SMOKE_TESTS_LOG_LEVEL} \
+            --config-file=/usr/certsuite/config/certsuite_config.yml \
+            --kubeconfig=/usr/certsuite/config/kubeconfig \
+            --label-filter="${SMOKE_TESTS_LABELS_FILTER}"
+
+      - name: Run sanity check on collector
+        id: collector_sanity_check
+        uses: ./.github/actions/run-sanity-check
+        with:
+          collector_username: ${COLLECTOR_CIUSER}
+          collector_password: ${COLLECTOR_CIPASSWORD}
